# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - dtdemo-video-index-uspklrodz4yzi

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://dtcontainerregister.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_055eb8ed94e14c638bc9f8107b3e95ee }}
        password: ${{ secrets.AzureAppService_ContainerPassword_2523c9779a4348f784f090378385fd41 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: dtcontainerregister.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_055eb8ed94e14c638bc9f8107b3e95ee }}/videosearch:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'dtdemo-video-index-uspklrodz4yzi'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_cf1825078f0646b7aa07dee3e86e3743 }}
        images: 'dtcontainerregister.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_055eb8ed94e14c638bc9f8107b3e95ee }}/videosearch:${{ github.sha }}'